name: 'Setup Node.js and Install Dependencies'
description: 'Common setup for Node.js and dependency installation using mise'
inputs:
  working-directory:
    description: 'Working directory for the installation'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Setup mise
      uses: jdx/mise-action@v2
      with:
        install: true

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        pnpm install --frozen-lockfile

    - name: Install Grit CLI
      shell: bash
      run: curl -fsSL https://docs.grit.io/install | bash

