/* auto-generated by NAPI-RS */
/* eslint-disable */
/** バッファの先頭バイトから画像フォーマットを判定する。 */
export declare function detectImageFormatJs(buffer: Buffer): string

/** EXIF 書き込み用パラメータ */
export interface JsExifWriteParams {
  /** 画像の説明（ワールド名など） */
  description: string
  /** 撮影日時 "yyyy:MM:dd HH:mm:ss" 形式 */
  dateTimeOriginal: string
  /** タイムゾーンオフセット "+09:00" 形式 */
  timezoneOffset: string
}

/** 画像サイズ（width/height）の読み取り結果 */
export interface JsImageDimensions {
  width: number
  height: number
}

/**
 * XMP バッチ読み取りの個別結果。
 *
 * エラーと「XMP なし」を区別するため、data/error を分離して返す。
 * - data が Some: XMP メタデータ抽出成功
 * - data が None かつ error が None: ファイルに XMP が存在しない（正常）
 * - data が None かつ error が Some: I/O エラーやパースエラー
 */
export interface JsVrcXmpBatchResult {
  data?: JsVrcXmpMetadata
  /** エラーが発生した場合のメッセージ。XMP なしの場合は null。 */
  error?: string
}

/** VRChat XMP メタデータ（読み取り結果） */
export interface JsVrcXmpMetadata {
  authorId?: string
  author?: string
  worldId?: string
  worldDisplayName?: string
}

/**
 * ファイルパスから画像サイズ（width/height）を読み取る。
 *
 * ファイルの先頭だけを部分読み込みするため、ファイル全体のデコードは不要。
 * PNG: 先頭 24 バイト（IHDR チャンク）から取得。
 * JPEG: 先頭 64KB をスキャンして SOF マーカーから取得。
 * エラー時（ファイル未検出、権限エラー、不明フォーマット、破損ヘッダー）は null を返す。
 */
export declare function readImageDimensions(filePath: string): JsImageDimensions | null

/**
 * 複数ファイルから画像サイズをバッチ読み取り。
 *
 * Rayon でスレッドプール並列化する。
 * 個別のファイルでエラーが発生しても null を返し、他のファイルの処理を続行する。
 */
export declare function readImageDimensionsBatch(filePaths: Array<string>): Array<JsImageDimensions | undefined | null>

/**
 * ファイルパスから VRChat XMP メタデータを読み取る（部分読み込み版）。
 *
 * VRChat メタデータが存在しなければ null を返す。
 * ファイル全体をメモリに載せず、チャンク/セグメントヘッダーだけ走査して
 * XMP データ部分だけを読み取る。
 *
 * 背景: 従来は fs::read でファイル全体（数MB）を読んでいたが、
 * XMP は PNG iTXt / JPEG APP1 に格納され先頭付近にあるため、
 * 部分読み込みで I/O を大幅に削減できる。
 */
export declare function readVrcXmp(filePath: string): JsVrcXmpMetadata | null

/**
 * 複数ファイルから VRChat XMP メタデータをバッチ読み取り（部分読み込み版）。
 *
 * Rayon でスレッドプール並列化する。各ファイルはチャンク/セグメントヘッダーだけ走査し、
 * XMP データ部分だけを読み取る（ファイル全体をメモリに載せない）。
 *
 * 戻り値は JsVrcXmpBatchResult の配列で、エラーと「XMP なし」を区別できる:
 * - data: Some, error: None → XMP 抽出成功
 * - data: None, error: None → XMP が存在しない（正常）
 * - data: None, error: Some → I/O エラー等
 */
export declare function readVrcXmpBatch(filePaths: Array<string>): Array<JsVrcXmpBatchResult>

/** バッファから VRChat XMP メタデータを読み取る。 */
export declare function readVrcXmpFromBuffer(buffer: Buffer): JsVrcXmpMetadata | null

/**
 * ファイルに EXIF メタデータを書き込む（アトミック書き込み：一時ファイル + rename）。
 *
 * ImageDescription, DateTimeOriginal, DateTimeDigitized, OffsetTime* を埋め込む。
 * クラッシュ時のファイル破損を防ぐため、同ディレクトリの .tmp ファイルに書き込んでから rename する。
 */
export declare function writeExif(filePath: string, params: JsExifWriteParams): void

/** バッファに EXIF メタデータを書き込んで新しいバッファを返す。 */
export declare function writeExifToBuffer(buffer: Buffer, params: JsExifWriteParams): Buffer
