/* auto-generated by NAPI-RS */
/* eslint-disable */
/** バッファの先頭バイトから画像フォーマットを判定する。 */
export declare function detectImageFormatJs(buffer: Buffer): string

/** EXIF 書き込み用パラメータ */
export interface JsExifWriteParams {
  /** 画像の説明（ワールド名など） */
  description: string
  /** 撮影日時 "yyyy:MM:dd HH:mm:ss" 形式 */
  dateTimeOriginal: string
  /** タイムゾーンオフセット "+09:00" 形式 */
  timezoneOffset: string
}

/** 画像サイズ（width/height）の読み取り結果 */
export interface JsImageDimensions {
  width: number
  height: number
}

/** VRChat XMP メタデータ（読み取り結果） */
export interface JsVrcXmpMetadata {
  authorId?: string
  author?: string
  worldId?: string
  worldDisplayName?: string
}

/**
 * VRChat XMP バッチ読み取り結果。
 * エラーと「XMP なし」を区別できる:
 * - data: Some, error: None → XMP 抽出成功
 * - data: None, error: None → XMP が存在しない（正常）
 * - data: None, error: Some → I/O エラー等
 */
export interface JsVrcXmpBatchResult {
  data?: JsVrcXmpMetadata | null
  error?: string | null
}

/**
 * ファイルパスから画像サイズ（width/height）を読み取る。
 *
 * ファイルの先頭だけを部分読み込みするため、ファイル全体のデコードは不要。
 * PNG: 先頭 24 バイト（IHDR チャンク）から取得。
 * JPEG: 先頭 64KB をスキャンして SOF マーカーから取得。
 * エラー時（ファイル未検出、権限エラー、不明フォーマット、破損ヘッダー）は null を返す。
 */
export declare function readImageDimensions(filePath: string): JsImageDimensions | null

/**
 * 複数ファイルから画像サイズをバッチ読み取り。
 *
 * Rayon でスレッドプール並列化する。
 * 個別のファイルでエラーが発生しても null を返し、他のファイルの処理を続行する。
 */
export declare function readImageDimensionsBatch(filePaths: Array<string>): Array<JsImageDimensions | undefined | null>

/**
 * ファイルパスから VRChat XMP メタデータを読み取る。
 *
 * VRChat メタデータが存在しなければ null を返す。
 * PNG の iTXt チャンク / JPEG の APP1 セグメントから XMP XML を抽出し、
 * roxmltree でパースして vrc: ネームスペースの属性を読む。
 */
export declare function readVrcXmp(filePath: string): JsVrcXmpMetadata | null

/**
 * 複数ファイルから VRChat XMP メタデータをバッチ読み取り。
 *
 * Rayon でスレッドプール並列化する。
 * 個別のファイルでエラーが発生しても null を返し、他のファイルの処理を続行する。
 */
export declare function readVrcXmpBatch(filePaths: Array<string>): Array<JsVrcXmpBatchResult>

/** バッファから VRChat XMP メタデータを読み取る。 */
export declare function readVrcXmpFromBuffer(buffer: Buffer): JsVrcXmpMetadata | null

/**
 * ファイルに EXIF メタデータを書き込む（アトミック書き込み：一時ファイル + rename）。
 *
 * ImageDescription, DateTimeOriginal, DateTimeDigitized, OffsetTime* を埋め込む。
 * クラッシュ時のファイル破損を防ぐため、同ディレクトリの .tmp ファイルに書き込んでから rename する。
 */
export declare function writeExif(filePath: string, params: JsExifWriteParams): void

/** バッファに EXIF メタデータを書き込んで新しいバッファを返す。 */
export declare function writeExifToBuffer(buffer: Buffer, params: JsExifWriteParams): Buffer
