name: license-checker

on:
  push:
    branches:
      - main
  schedule:
    # 1/1month
    - cron: '0 0 1 * *'

jobs:
  license-checker:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Setup Node and Install Dependencies
          uses: ./.github/actions/setup-node-and-install
        
        - name: run license-checker
          run: |
            nr license-check:validate
