name: license-checker

on:
  push:
    branches:
      - main
  schedule:
    # 1/1month
    - cron: '0 0 1 * *'

jobs:
  license-checker:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Setup Node and Install Dependencies
          uses: ./.github/actions/setup-node-and-install
          with:
            # license-checker は node_modules の package.json を読むだけ
            include-native: 'false'

        - name: run license-checker
          run: |
            pnpm license-check:validate
