name: Lint and Test

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      
      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: lint
        run: yarn lint && yarn type-check

      - name: test
        run: yarn test
