name: Lint and Test

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - run: npm i -g @antfu/ni
      
      - name: install dependencies
        run: nci

      - name: lint
        run: nr lint && nr type-check

      - name: test
        run: nr test
