name: 'PR Issue Link'
on:
  pull_request:
    types: [opened]

jobs:
  issue-links:
    runs-on: ubuntu-22.04
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      pull-requests: write
    steps:
      - uses: tkt-actions/add-issue-links@v1.8.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}' # required
          branch-prefix: '' # required
          link-style: comment
