name: 'PR Issue Link'
on:
  pull_request:
    types: [opened]

jobs:
  issue-links:
    runs-on: ubuntu-22.04
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: tkt-actions/add-issue-links@v1.9.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}' # required
          # 抽出される: 123/fix/hogehoge -> 123, 456/feat/new-feature -> 456
          # 抽出されない: 123xyz/hogehoge -> null, hoge/123/hogehoge -> null, feat/123 -> null
          branch-prefix: '^(\d+)/' # required
          link-style: comment
          # Automatically assign the pull request creator to the related issue
          assign-pr-creator-to-issue: 'true'
