name: Tag on Push to Main

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup bun
        uses: oven-sh/setup-bun@v1

      - run: npm i -g @antfu/ni
      
      - name: install dependencies
        run: nci

      - name: lint
        run: nr lint && nr type-check

  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # NOTE @v2 uses the token as an auth http header. Set it to
          # a Personal Access Token instead of secrets.GITHUB_TOKEN
          # so that tag pushes trigger repo push events.
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          tag_string="build-$(date -u +%Y%m%d%H%M%S)-${GITHUB_SHA::8}"
          git tag "$tag_string"
          git push origin "$tag_string"
