name: Tag on Push to Main

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - run: npm i -g @antfu/ni

      - name: install dependencies
        run: nci

      - name: lint
        run: nr lint

  changelog:
    name: Generate changelog
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit
        run: |
          git checkout ${{ github.ref_name }}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git ${{ github.ref_name }}

  create_tag:
    needs: [lint, changelog]
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # NOTE @v2 uses the token as an auth http header. Set it to
          # a Personal Access Token instead of secrets.GITHUB_TOKEN
          # so that tag pushes trigger repo push events.
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}

      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          tag_string="build-$(date -u +%Y%m%d%H%M%S)-${GITHUB_SHA::8}"
          git tag "$tag_string"
          git push origin "$tag_string"
