name: Update Changelog

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Get version info
        id: version_info
        run: |
          # mainブランチのpackage.jsonのバージョンを取得
          git fetch origin main
          main_version=$(git show origin/main:package.json | node -p "require('/dev/stdin').version")
          echo "main_version=$main_version" >> $GITHUB_OUTPUT
          
          # 現在のブランチのバージョンを取得
          current_version=$(node -p "require('./package.json').version")
          echo "current_version=$current_version" >> $GITHUB_OUTPUT
          
          # バージョンが異なるかチェック
          if [ "$main_version" != "$current_version" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate Changelog
        if: steps.version_info.outputs.version_changed == 'true'
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --output CHANGELOG.md

      - name: Commit Changes
        if: steps.version_info.outputs.version_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add CHANGELOG.md
          git commit -m "doc: update changelog for version ${{ steps.version_info.outputs.current_version }}"
          git push origin ${{ github.head_ref }} 