name: Update Changelog

on:
  push:
    tags:
      # - 'v*'
      - '*'

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get version from tag
        id: get-version
        uses: battila7/get-version-action@v2

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit changes
        run: |
          VERSION=${{ steps.get-version.outputs.version-without-v }}
          BRANCH="release/${VERSION}"
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git switch -c $BRANCH
          git add CHANGELOG.md
          git commit -m "Bump version to $VERSION"
          git push --set-upstream origin $BRANCH

      - name: Create Pull Request
        run: |
          VERSION=${{ steps.get-version.outputs.version-without-v }}
          BRANCH="release/${VERSION}"
          gh pr create --title "Update CHABGELOG.md" --body "Update CHABGELOG.md for $VERSION" --base main --head $BRANCH --delete-branch
          
