name: Build and Release Electron App (Cross Platform)

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    outputs:
      app-version: ${{ steps.app-version.outputs.version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - run: npm i -g @antfu/ni

      - name: Install dependencies
        run: nci

      - name: output version
        id: app-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Build Electron app
        run: nr dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-v${{ steps.app-version.outputs.version }}-
          path: |
            dist/*
  
  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      WIN_ARTIFACT: app-windows-latest-v${{ needs.build.outputs.app-version }}
      UBUNTU_ARTIFACT: app-ubuntu-latest-v${{ needs.build.outputs.app-version }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Zip artifacts
        run: |
          zip -r "${WIN_ARTIFACT}.zip" "${WIN_ARTIFACT}"
          zip -r "${UBUNTU_ARTIFACT}.zip" "${UBUNTU_ARTIFACT}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.WIN_ARTIFACT }}.zip
            ${{ env.UBUNTU_ARTIFACT }}.zip
          tag_name: ${{ github.ref }}
          body: |
            Release for ${{ github.ref }}
          draft: true
          prerelease: false
