name: PR Screenshot Commenter

on:
  pull_request:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - run: npm i -g @antfu/ni

      - name: Install dependencies
        run: ni

      - name: build app
        run: nr build

      - name: Install Playwright Browsers
        run: nr playwright install --with-deps
      - name: Run Playwright tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- nr playwright test
      
      - name: upload screenshot
        id: upload-screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: intro.png

      - name: Comment PR with screenshot
        uses: actions/github-script@v7
        env:
          screenshotUrl: ${{ steps.upload-screenshot.outputs.artifact-url }}
        with:
          script: |
            const screenshotPath = process.env.screenshotUrl;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '![screenshot](' + screenshotPath + ')'
            });
