name: PR Screenshot Commenter

on:
  pull_request:

jobs:
  screenshot:
    runs-on: ubuntu-22.04
    permissions:
      contents: write # Changed from read to write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - run: npm i -g @antfu/ni

      - name: Install dependencies
        run: nci

      - name: build app
        run: nr build

      - name: Install Playwright Browsers
        run: nr playwright install --with-deps
      - name: Run Playwright tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- nr playwright test

      - name: upload screenshot
        id: upload-screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: playwright/previews/*.png

      - name: Publish screenshot to branch
        env:
          BRANCH: pr-screenshot-${{ github.event.pull_request.number }}-${{ github.run_id }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SCREENSHOT_DIR="playwright/previews"
          # Find all PNG files in the directory
          SCREENSHOT_FILES=$(find "$SCREENSHOT_DIR" -maxdepth 1 -name '*.png')

          if [ -z "$SCREENSHOT_FILES" ]; then
            echo "No PNG screenshots found in $SCREENSHOT_DIR"
            exit 1
          fi

          echo "Found screenshots:"
          echo "$SCREENSHOT_FILES"

          mkdir upload
          for file in $SCREENSHOT_FILES; do
            cp "$file" upload/
          done

          cd upload
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Add screenshot for PR #${{ github.event.pull_request.number }}"
          git branch -M "$BRANCH"
          git remote add origin "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git"
          git push origin "$BRANCH" --force

      - name: Comment with screenshot
        env:
          BRANCH: pr-screenshot-${{ github.event.pull_request.number }}-${{ github.run_id }}
          REPO: ${{ github.repository }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Screenshots for this PR:
            <details>
            <summary>Click to expand</summary>

            ${{ steps.generate_comment.outputs.body }}
            </details>
          pr_number: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate comment body
        id: generate_comment
        env:
          BRANCH: pr-screenshot-${{ github.event.pull_request.number }}-${{ github.run_id }}
          REPO: ${{ github.repository }}
        run: |
          cd upload
          comment_body=""
          for file in $(git ls-tree --name-only HEAD); do
            comment_body="${comment_body}![](https://raw.githubusercontent.com/${REPO}/${BRANCH}/${file})\n"
          done
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$comment_body" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
