name: PR Screenshot Commenter

on:
  pull_request:

jobs:
  screenshot:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - run: npm i -g @antfu/ni

      - name: Install dependencies
        run: nci

      - name: build app
        run: nr build

      - name: Install Playwright Browsers
        run: nr playwright install --with-deps
      - name: Run Playwright tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- nr playwright test

      - name: upload screenshot
        id: upload-screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: playwright/previews/*.png

      - name: Comment PR with screenshot
        uses: actions/github-script@v7
        env:
          screenshotPath: './playwright/previews/'
        with:
          script: |
            const path = require('path');
            const fs = require('fs');
            const screenshotDir = path.resolve(process.env.screenshotPath);
            const screenshots = fs.readdirSync(screenshotDir).filter(f => f.endsWith('.png'));
            if (screenshots.length === 0) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'No screenshot generated.'
              });
            } else {
              const bodies = screenshots.map(file => {
                const base64 = fs.readFileSync(path.join(screenshotDir, file), 'base64');
                return `![${file}](data:image/png;base64,${base64})`;
              });
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: bodies.join('\n')
              });
            }
